# Generated by Django 3.0.7 on 2020-06-11 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0016_auto_20200610_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'ordering': ['name']},
        ),
    ]
