# Generated by Django 3.0.7 on 2020-06-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0019_auto_20200616_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='books',
            field=models.ManyToManyField(related_name='books', to='p_library.Book'),
        ),
    ]
