# Generated by Django 3.0.7 on 2020-06-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0020_friend_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='books', to='p_library.Book'),
        ),
    ]
