# Generated by Django 3.0.7 on 2020-06-17 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0021_auto_20200616_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birth_year',
            field=models.SmallIntegerField(verbose_name='Год рождения'),
        ),
        migrations.AlterField(
            model_name='author',
            name='country',
            field=models.CharField(max_length=2, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='author',
            name='full_name',
            field=models.TextField(verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_author', to='p_library.Author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='book',
            name='copy_count',
            field=models.SmallIntegerField(default=0, verbose_name='Кол-во копий'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='book',
            name='friend_reader',
            field=models.ManyToManyField(related_name='reader', to='p_library.Friend', verbose_name='Читающие друзья'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='p_library.Publisher', verbose_name='Издатель'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.TextField(verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year_release',
            field=models.SmallIntegerField(verbose_name='Год издания'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='books', to='p_library.Book', verbose_name='Книги'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='name',
            field=models.TextField(verbose_name='Имя друга'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.TextField(verbose_name='Название издательства'),
        ),
    ]
