# Generated by Django 3.0.7 on 2020-06-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0023_auto_20200619_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='copy_count',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='book',
            name='friend_reader',
            field=models.ManyToManyField(blank=True, related_name='book_reader', to='p_library.Friend', verbose_name='Читающие друзья'),
        ),
    ]
