# Generated by Django 3.0.7 on 2020-06-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0024_auto_20200619_1152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['full_name']},
        ),
        migrations.AlterModelOptions(
            name='friend',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
