# Generated by Django 3.0.7 on 2020-06-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0025_auto_20200624_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, upload_to='book_covers'),
        ),
    ]
